// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Projeto.Data;

#nullable disable

namespace Projeto.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240202231604_Destino")]
    partial class Destino
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Projeto.Model.ProjetoAgencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Foto")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NomeDestino")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PromocoesDestino")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ValorDestino")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ValorPromocionalDestino")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("projeto");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "São mais de 40 praias ao redor da ilha principal, além de outras ilhotas que fazem parte do arquipélago. Além disso, com 83% de Mata Atlântica preservada, o Parque Estadual de Ilhabela tem atrações de ecoturismo para todos os perfis, de famílias com crianças aos mais aventureiros. Possui um território de 348 km², 36 Km de praias e ainda, possui 360 cachoeiras, além disso, ela é um dos únicos municípios-arquipélagos marinhos do Brasil. Uma maravilha de Arquipélago.",
                            Foto = "https://karinabertolazzo.github.io/PrimeiraEntrega/assets/img/card_ilhadascabras.jpeg",
                            NomeDestino = "IlhaBela",
                            PromocoesDestino = "Promoção 1",
                            ValorDestino = "R$ 590",
                            ValorPromocionalDestino = "R$ 390"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
