// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Projeto.Data;

#nullable disable

namespace Projeto.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Projeto.Model.ProjetoAgencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Foto")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NomeDestino")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PromocoesDestino")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ValorDestino")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ValorPromocionalDestino")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("projeto");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "São mais de 40 praias ao redor da ilha principal, além de outras ilhotas que fazem parte do arquipélago. Além disso, com 83% de Mata Atlântica preservada, o Parque Estadual de Ilhabela tem atrações de ecoturismo para todos os perfis, de famílias com crianças aos mais aventureiros. Possui um território de 348 km², 36 Km de praias e ainda, possui 360 cachoeiras, além disso, ela é um dos únicos municípios-arquipélagos marinhos do Brasil. Uma maravilha de Arquipélago.",
                            Foto = "https://raw.githubusercontent.com/karinabertolazzo/PrimeiraEntrega/main/assets/img/card_ilhadascabras.jpeg",
                            NomeDestino = "IlhaBela",
                            PromocoesDestino = "Promoção 1",
                            ValorDestino = "R$ 590",
                            ValorPromocionalDestino = "R$ 390"
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "As Maldivas estão entre os melhores lugares do mundo para mergulhar. São quase 30 espécies de tubarões, mantas gigantes e vida marinha avassaladora. Os melhores meses para o mergulho são de dezembro a março, no auge da alta temporada, quando as águas do mar ficam ainda mais cristalinas. Nadar ao lado de peixes coloridos, fazer um cruzeiro por várias ilhas, jantar em um restaurante subaquático e até mergulhar em um “mar de estrelas”.",
                            Foto = "https://raw.githubusercontent.com/karinabertolazzo/PrimeiraEntrega/main/assets/img/card_maldivas.jpg",
                            NomeDestino = "Maldivas",
                            PromocoesDestino = "Promoção 2",
                            ValorDestino = "R$ 2.464",
                            ValorPromocionalDestino = "R$ 2000"
                        },
                        new
                        {
                            Id = 3,
                            Descricao = "Zanzibar é uma ilha sensacional localizada no sudeste do continente africano. Ainda pouco conhecido pelos viajantes, o destino é exótico, o que colabora para dar um ar roots ao lugar. E um detalhe importante: o arquipélago é banhado pelas águas do oceano Pacífico. Zanzibar é um prato cheio para viajantes que gostam de lugares exóticos e com muitas belezas naturais, mas que prezam pelo fator cultural. visite alguns pontos turísticos.",
                            Foto = "https://raw.githubusercontent.com/karinabertolazzo/PrimeiraEntrega/main/assets/img/card_zanzibar.jpg",
                            NomeDestino = "Zamzimar",
                            PromocoesDestino = "Promoção 3",
                            ValorDestino = "R$ 2.199",
                            ValorPromocionalDestino = "R$ 2000"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
